### ISSUE TITLE
If "-o" is not set, default to the current working directory

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#10]
This is another minor issue, but it would be nice if the default output folder was the current working directory.  I haven't dug into how this part of the code is structured, but on some of my other tools I have got this to work by setting the default value in the argparser add_argument call (https://docs.python.org/3/library/argparse.html#default).

Right now, if "-o" is not set, I get the following traceback:
```
Traceback (most recent call last):
  File "c:\miniconda3\envs\landsat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\landsat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\landsat\Scripts\landsat.exe\__main__.py", line 9, in <module>
  File "c:\miniconda3\envs\landsat\lib\site-packages\core\landsat.py", line 81, in __main__
    exit(main(args))
  File "c:\miniconda3\envs\landsat\lib\site-packages\core\landsat.py", line 69, in main
    dry_run=args.return_list, zipped=args.zipped)
  File "c:\miniconda3\envs\landsat\lib\site-packages\core\download_composer.py", line 64, in downloa
d_landsat
    satellite, tile[0], tile[1]))
  File "c:\miniconda3\envs\landsat\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by dgketchum** [comment]
added default os.getcwd()
