### ISSUE TITLE
NotImplementedError for image ID L080430302015041LGN01

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#20]
I am getting the error/traceback listed below when the script tries to download OLI-only images (e.g. L080430302015041LGN01).  This is using the latest version on PyPi (0.3.86) and the following command line call.  I'm not sure the most logical way to handle it, but you could allow the user to specify "L08" as a satellite option and then exclude L08 images from LC8.

`landsat --satellite LC8 --start 2015-02-01 --end 2015-02-15 -p 43 -r 30 -o .\ -cred .\usgs.txt`

```
Namespace(configuration=None, credentials='.\\usgs.txt', end='2015-02-15', latitude=None, longitude=
None, max_cloud_percent=100, output='.\\', path='43', return_list=False, row='30', satellite='LC8',
start='2015-02-01', zipped=False)

Starting download with pathrow...
LO80430302015041LGN01
Traceback (most recent call last):
  File "c:\miniconda3\envs\landsat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\landsat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\landsat\Scripts\landsat.exe\__main__.py", line 9, in <module>
  File "c:\miniconda3\envs\landsat\lib\site-packages\landsat\landsat.py", line 133, in cli_runner
    return main(args)
  File "c:\miniconda3\envs\landsat\lib\site-packages\landsat\landsat.py", line 124, in main
    scenes = download_landsat(start, end, sat, **cfg)
  File "c:\miniconda3\envs\landsat\lib\site-packages\landsat\download_composer.py", line 68, in down
load_landsat
    usgs_creds, zipped)
  File "c:\miniconda3\envs\landsat\lib\site-packages\landsat\usgs_download.py", line 144, in down_us
gs_by_list
    identifier, stations = get_station_list_identifier(product)
  File "c:\miniconda3\envs\landsat\lib\site-packages\landsat\usgs_download.py", line 104, in get_sta
tion_list_identifier
    raise NotImplementedError('Must provide valid product string...')
NotImplementedError: Must provide valid product string...
```

**Comment by dgketchum** [comment]
This image is not available at Tier 1 level in Google Storage
