### ISSUE TITLE
Return more helpful error message when neither path/row and lat/lon are set

### ISSUE THREAD

**Issue by cgmorton** [dgketchum/Landsat578#5]
Currently the script returns the following traceback and error:
```
Traceback (most recent call last):
  File "c:\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\Scripts\landsat.exe\__main__.py", line 9, in <module>
  File "c:\miniconda3\lib\site-packages\landsat\landsat.py", line 78, in __main__
    exit(main(args))
  File "c:\miniconda3\lib\site-packages\landsat\landsat.py", line 70, in main
    raise NotImplementedError('Was not executed.')
NotImplementedError: Was not executed.
```

**Comment by jirhiker** [comment]
typically NotImplementedError's are reserved when building "interfaces"

its a warning to users of the class that their subclass needs to define something

```class VehicleInterface:
            def move(self, *args, **kw):
                   raise NotImplementedError('please define the move method")
          
     class Car(VehicleInterface):
            def move(self, *args, **kw):
                   self.select_gear()
                   self.foot_to_accelerator()
```

if i then came in and wanted to add `class Plane(VehicleInterface)` I know i have to implement `Plane.move`

**Comment by dgketchum** [comment]
added few arguments exception
